platform :ios, '8.0'

target 'Yuanqu' do
pod 'AFNetworking'
pod 'Masonry'
pod 'MJExtension'
pod 'SDCycleScrollView'
pod 'RDVTabBarController'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'AMap3DMap-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'YTKNetwork'
pod 'UITableView+FDTemplateLayoutCell'
pod 'WebViewJavascriptBridge'
pod 'MBProgressHUD'
pod 'ProgressHUD'
pod 'OpenShare'
pod 'JCAlertController'
pod 'VVBlurPresentation'
end
